name: sonarqube

on:
  workflow_dispatch:
  push:

jobs:
  trigger:
    name: Trigger main workflow
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another workflow
        if: github.ref != 'refs/heads/main'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: sonarqube.yml
          token: ${{ secrets.GH_TOKEN }}
          repo: The-A-Team-organization/illuminati_frontend
          ref: main
      - name: Wait 1m
        if: github.ref != 'refs/heads/main'
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: "1m"
      - name: Success
        run: echo Success

  build:
    needs: trigger
    name: SonarQube analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tox and any other packages
        run: pip install tox

      - name: Run tox
        run: tox -e py

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        continue-on-error: false
        with:
          args: >-
            -Dsonar.projectKey=illuminati_backend
            -Dsonar.sources=.
            -Dsonar.coverage.exclusions=**/urls.py,tests/**,core/**,enums/**,api/**,manage.py
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
